### ISSUE TITLE
Semantic segmentation label of the result at different scale

### ISSUE THREAD

**Issue by Batwho** [Pointcept/SAMPart3D#13]
Hello,

Thank you very much for sharing the code of your great project. I do have a question after running SAMPart3D on my own data.
After I finished training the MLP the output results folder have the output .npy and meshes are saved in vis_pcd. Then, is the semantics segmention like the PartObjaverse-Tiny_semantic.json saved somewhere? I assume for each scale, there should be a separate semantic json dict.

**Comment by yhyang-myron** [comment]
Hi, Thanks for your interest in our work!
The output results from training the MLP do not include semantic information. If you would like to obtain semantic details, you can use the script `python tools/highlight_parts.py` to highlight the parts and consult the LLM.

**Comment by Batwho** [comment]
I see, thank you very much!
