### ISSUE TITLE
Are there any plans to release the model checkpoints?

### ISSUE THREAD

**Issue by Georgefwt** [Pointcept/SAMPart3D#2]
First of all, congratulations on your great work. I'm very interested in this proj and would like to know about the checkpoint release plans:

Are there any plans to release the model checkpoints?
If so, is there an expected timeline for the release?

**Comment by yhyang-myron** [comment]
Hi, Thanks for your interest in our work!
The checkpoint is released at [https://huggingface.co/yhyang-myron/SAMPart3D/tree/main](https://huggingface.co/yhyang-myron/SAMPart3D/tree/main).

**Comment by Georgefwt** [comment]
can you upload "knight.glb" to make it easier for out testing?

**Comment by Georgefwt** [comment]
I'm a bit confused by this part of the README:

```bash
SAMPart3D
|-- ckpt
    |-- ptv3-object.pth
|-- mesh_root
    |-- knight.glb
|-- data_root
    |-- knight
        |-- meta.json
        |-- render_0000.webp
        |-- depth_0000.exr
        ...
```
```bash
export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
sh scripts/train.sh -g ${NUM_GPU} -d ${DATASET_NAME} -c ${CONFIG_NAME} -n ${EXP_NAME} -o ${OBJECT_UID}
```

Does that mean I have to train different models for each object?

**Comment by yhyang-myron** [comment]
Hi, thanks for your interest in our work!
1. The knight.glb is uploaded at [https://huggingface.co/yhyang-myron/SAMPart3D/tree/main](https://huggingface.co/yhyang-myron/SAMPart3D/tree/main).
2. Yes, lightweight MLPs need to be trained for each object.
