### ISSUE TITLE
PartObjaverse-Tiny segmentation ground truth tooling

### ISSUE THREAD

**Issue by vishalkothari** [Pointcept/SAMPart3D#5]
Hi, Which tool was used to generate semantic and instance level ground truths for PartObjaverse-Tiny?
I would like to use the same for re-training and testing.

**Comment by ethenchen-tc** [comment]
I am also interested in the annotation tools. Look forward for the answer.

**Comment by yhyang-myron** [comment]
Hi, Thanks for your interest in our work!
we manually annotate the PartObjaverse-Tiny dataset.
Maybe you can try to use blender.
